//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
using namespace drogon;
class ListParameters:public DrTemplate<ListParameters>
{
public:
	ListParameters(){};
	virtual ~ListParameters(){};
	virtual std::string genText(const DrTemplateData &) override;
};